// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXZKzVsr9-YtHrnxu0Ax5a_FUPbVfJOJ4',
    appId: '1:885370450278:web:1e4ccb09026632c1ee58a7',
    messagingSenderId: '885370450278',
    projectId: 'nitbit2-7f960',
    authDomain: 'nitbit2-7f960.firebaseapp.com',
    storageBucket: 'nitbit2-7f960.firebasestorage.app',
    measurementId: 'G-43T0WR5H2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIY9c-WPqnpWy9rviUxiDlUi6FoajoLUY',
    appId: '1:885370450278:android:1ed7de1eb01a54f5ee58a7',
    messagingSenderId: '885370450278',
    projectId: 'nitbit2-7f960',
    storageBucket: 'nitbit2-7f960.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1fGa6hYEAds8jaS3ououTW6-W7wI2ChY',
    appId: '1:885370450278:ios:afa6561fe988f613ee58a7',
    messagingSenderId: '885370450278',
    projectId: 'nitbit2-7f960',
    storageBucket: 'nitbit2-7f960.firebasestorage.app',
    iosBundleId: 'com.example.nitbitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1fGa6hYEAds8jaS3ououTW6-W7wI2ChY',
    appId: '1:885370450278:ios:afa6561fe988f613ee58a7',
    messagingSenderId: '885370450278',
    projectId: 'nitbit2-7f960',
    storageBucket: 'nitbit2-7f960.firebasestorage.app',
    iosBundleId: 'com.example.nitbitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXZKzVsr9-YtHrnxu0Ax5a_FUPbVfJOJ4',
    appId: '1:885370450278:web:7fe25bb958124866ee58a7',
    messagingSenderId: '885370450278',
    projectId: 'nitbit2-7f960',
    authDomain: 'nitbit2-7f960.firebaseapp.com',
    storageBucket: 'nitbit2-7f960.firebasestorage.app',
    measurementId: 'G-YBT7QPC2ZM',
  );

}